services:
  - type: web
    name: paradise-point-housing
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false